# Generated by Django 5.2.17 on 2026-08-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ["username"]},
        ),
    ]
